config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :products, except: :show
  resources :brands, except: :show

  # Defines the root path route ("/")
  root 'brands#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
  validates :name, presence: true

  scope :alphabetical, -> { order(:name) }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand, optional: true

  validates :name, presence: true
  validates :price, numericality: { greater_than: 0, less_than_or_equal_to: 100 }

  scope :alphabetical, -> { order(:name) }

  def self.total_price
    sum(:price)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Bali::LayoutConcern

  default_form_builder Bali::FormBuilder
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: %i[edit update destroy]

  def index
    @brands = Brand.alphabetical
  end

  def new
    @brand = Brand.new
  end

  def edit; end

  def create
    @brand = Brand.new(brand_params)

    if @brand.save
      redirect_to brands_url, notice: 'Brand was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @brand.update(brand_params)
      redirect_to brands_url, notice: 'Brand was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.turbo_stream
    end
  end

  private

  def set_brand
    @brand = Brand.find(params[:id])
  end

  def brand_params
    params.require(:brand).permit(:name)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[edit update destroy]
  before_action :set_brands, only: %i[new create edit update]

  def index
    @products = Product.alphabetical
    @total_product_price = Product.total_price
  end

  def new
    @product = Product.new
  end

  def edit; end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_url, notice: 'Product was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @product.update(product_params)
      redirect_to products_url, notice: 'Product was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy
    @total_product_price = Product.total_price

    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.turbo_stream
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :brand_id, :description, :price)
  end

  def set_brands
    @brands = Brand.alphabetical
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Bali::FormHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/brands/_brand.html.erb
<%= turbo_frame_tag dom_id(brand) do %>
  <div class="columns">
    <div class="column is-1">
      <%= render Bali::Link::Component.new(icon_name: 'edit', href: edit_brand_path(brand), modal: true) %>
    </div>
    <div class="column">
      <%= brand.name %>
    </div>
  </div>
<% end %>

app/views/brands/_form.html.erb
<%= form_with(model: brand) do |form| %>
  <%= form.text_field_group :name %>
  
  <br>
  <%= form.submit_actions 'Save', modal: true, class: 'button is-primary' %>
<% end %>

app/views/brands/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@brand) %>

<%= turbo_stream.replace 'modal-template' do %>
  <%= render Bali::Modal::Component.new(active: false) %>
<% end %>

app/views/brands/edit.html.erb
<%= render Bali::PageHeader::Component.new(title: 'Edit Brand') do %>
  <%= render Bali::DeleteLink::Component.new(name: 'Delete', href: @brand,
                                             confirm: 'Are you sure you want to delete this brand?') %>
<% end %>


<%= render "form", brand: @brand %>

app/views/brands/index.html.erb
<h1 class="title">Brands</h1>

<%= render Bali::Link::Component.new(name: 'New brand', href: new_brand_path, modal: true, class: 'button is-primary') %>
<hr>

<%= turbo_frame_tag 'brands' do %>
  <div class="columns">
    <div class="column is-1"></div>
    <div class="column">NAME</div>
  </div>

  <% @brands.each do |brand| %>
    <%= render brand %>
  <% end %>
<% end %>

app/views/brands/new.html.erb
<h1 class="title">New Brand</h1>

<%= render "form", brand: @brand %>

app/views/layouts/_notifications.html.erb
<% if notice %>
  <%= render Bali::Notification::Component.new(type: :success) do %>
    <%= notice %>
  <% end %>
<% end %>

<% if alert %>
  <%= render Bali::Notification::Component.new(type: :danger) do %>
    <%= alert %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

 <body data-controller="modal">
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <%= link_to "All Brands", brands_path, class: 'navbar-item' %>
          <%= link_to "All Products", products_path, class: 'navbar-item' %>
        </div>
      </div>
    </nav>

    <section class="section">
      <div class="container">
        <%= render 'layouts/notifications' %>
        <%= yield %>
      </div>
    </section>

    <%= render Bali::Modal::Component.new(active: false) %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <%= form.text_field_group :name %>

  <%= form.select_group :brand_id, @brands.pluck(:name, :id), { include_blank: true } %>

  <%= form.text_area_group :description%>

  <%= form.number_field_group :price %>
  
  <%= form.submit_actions 'Save', modal: true, class: 'button is-primary' %>
<% end %>

app/views/products/_product.html.erb
<%= turbo_frame_tag dom_id(product) do %>
  <div class="columns">
    <div class="column is-1">
      <%= render Bali::Link::Component.new(icon_name: 'edit', href: edit_product_path(product), modal: true) %>
    </div>
    <div class="column">
      <%= product.name %>
    </div>
    <div class="column">
      <%= product.brand&.name %>
    </div>
    <div class="column">
      <%= product.description %>
    </div>
    <div class="column">
      <%= product.price %>
    </div>
  </div>
<% end %>

app/views/products/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@product) %>

<%= turbo_stream.update 'total_product_price' do %>
  Total price: <%= number_to_currency @total_product_price %>
<% end %>


<%= turbo_stream.replace 'modal-template' do %>
  <%= render Bali::Modal::Component.new(active: false) %>
<% end %>

app/views/products/edit.html.erb
<%= render Bali::PageHeader::Component.new(title: 'Edit Product') do %>
  <%= render Bali::DeleteLink::Component.new(name: 'Delete', href: @product,
                                             confirm: 'Are you sure you want to delete this product?') %>
<% end %>

<%= render "form", product: @product %>

app/views/products/index.html.erb
<h1 class="title">Products</h1>
<h2 class="subtitle", id='total_product_price'>
  Total price: <%= number_to_currency @total_product_price %>
</h2>

<%= render Bali::Link::Component.new(name: 'New product', href: new_product_path, modal: true, class: 'button is-primary') %>
<hr>

<%= turbo_frame_tag 'products' do %>
  <div class="columns">
    <div class="column is-1"></div>
    <div class="column">NAME</div>
    <div class="column">BRAND</div>
    <div class="column">DESCRIPTION</div>
    <div class="column">PRICE</div>
  </div>
  <% @products.each do |product| %>
    <%= render product %>
  <% end %>
<% end %>

app/views/products/new.html.erb
<h1 class="title">New Product</h1>

<%= render "form", product: @product %>